# Generated by Django 4.0.1 on 2022-06-21 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EQSecurity',
            fields=[
                ('symbol', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('value', models.IntegerField()),
                ('isin', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'EQSecurity',
                'verbose_name_plural': 'EQSecurities',
            },
        ),
        migrations.CreateModel(
            name='Bhavcopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=3)),
                ('date', models.DateField()),
                ('prev_close', models.FloatField()),
                ('open_price', models.FloatField()),
                ('high_price', models.FloatField()),
                ('low_price', models.FloatField()),
                ('last_price', models.FloatField()),
                ('close_price', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('ttl_qnty', models.IntegerField()),
                ('turnover', models.FloatField()),
                ('trades', models.IntegerField()),
                ('deliv_qty', models.IntegerField()),
                ('deliv_per', models.FloatField()),
                ('symbol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='apis.eqsecurity')),
            ],
        ),
    ]
